DROP TABLE IF EXISTS mainmenu;

CREATE TABLE IF NOT EXISTS mainmenu(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL,
  page_title TEXT NOT NULL
);

INSERT INTO mainmenu (url, page_title) VALUES
  ('/main', 'Главная страница'),
  ('/user_profile', 'Профиль'),
  ('/add_word', 'Добавить слово'),
  ('/edit_word', 'Изменить слово'),
  ('/delete_word', 'Удалить слово'),
  ('/show_words/1', 'Показать слова');

DROP TABLE IF EXISTS user_words;

CREATE TABLE IF NOT EXISTS user_words(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  word_number INTEGER NOT NULL,
  eng_word TEXT,
  rus_word TEXT,
  word_examples TEXT,
  word_description TEXT,
  add_date TEXT
);

INSERT INTO user_words (user_id, word_number, eng_word, rus_word, add_date) VALUES
  ("0","0","fridge","холодильник", date()),
  ("0","1","freezer","морозильник", date()),
  ("0","2","magnets","магниты", date()),
  ("0","3","dining room table","стол для трапез", date()),
  ("0","4","kitchen chairs","кухонные стулья", date()),
  ("0","5","dining room chairs","кухонные стулья", date()),
  ("0","6","high chair","стул для ребёнка", date()),
  ("0","7","a stand-alone hight chair","отдельно стоящий стул для ребёнка", date()),
  ("0","8","kitchen counter","стол для резки, готовки пищи", date()),
  ("0","9","fruit tray","система подносов для фруктов", date()),
  ("0","10","tangerine","мандарин", date()),
  ("0","11","coaster","подставка для стаканов", date()),
  ("0","12","coffee grinder","кофемолка", date()),
  ("0","13","coffee bean","кофейное зерно", date()),
  ("0","14","sippy cup","кружка-непроливайка", date()),
  ("0","15","chees grater","тёрка для сыра", date()),
  ("0","16","knives","ножи", date()),
  ("0","17","measuring cups","мерные стаканьчики", date()),
  ("0","18","tablespons","столовые ложки", date()),
  ("0","19","teaspons","чайные ложки", date()),
  ("0","20","condiment","специи", date()),
  ("0","21","honey","мёд", date()),
  ("0","22","balsamic vinegar","бальзамический уксус", date()),
  ("0","23","chopsticks","палочки для еды, китайские палочки", date()),
  ("0","24","salt","соль", date()),
  ("0","25","olive oil","оливковое масло", date()),
  ("0","26","green thumb","", date()),
  ("0","27","oven","духовка / вся плита", date()),
  ("0","28","stovetop","плита / верхняя часть плиты", date()),
  ("0","29","burner","комфорка", date()),
  ("0","30","cooker","плита + духовка", date()),
  ("0","31","nobs","переключатели на плите", date()),
  ("0","32","stickler / picky","ярый сторонник", date()),
  ("0","33","pot","кастрюля", date()),
  ("0","34","pan","сковорода", date()),
  ("0","35","a glass lid","стеклянная крышка", date()),
  ("0","36","butternut squash","тыква с орехами", date()),
  ("0","37","butternut","ореховый", date()),
  ("0","38","squash","кабачек", date()),
  ("0","39","oven mitts","перчатки для духовки", date()),
  ("0","40","spice rack/cabin","комната для специй", date()),
  ("0","41","spice shelf","полка для специй", date()),
  ("0","42","tea","чай", date()),
  ("0","43","cook book","кулинарная книга", date()),
  ("0","44","dirty dishes","грязная посуда", date()),
  ("0","45","a sink","раковина", date()),
  ("0","46","faucet","смеситель", date()),
  ("0","47","strainer","друшлак", date()),
  ("0","48","colander","сито", date()),
  ("0","49","dishwasher","посудомойка", date()),
  ("0","50","air conditioner","кондиционер", date()),
  ("0","51","heating","отопление", date()),
  ("0","52","[cloth] washer","стриальная машина", date()),
  ("0","53","dryer","сушилка", date()),
  ("0","54","table top dish washer","настольная посудомойка", date()),
  ("0","55","dish rack","стойка для посуды", date()),
  ("0","56","rack","стеллаж", date()),
  ("0","57","shelf","полка", date()),
  ("0","58","hand wash","ручшая стрика, мойка", date()),
  ("0","59","hand dry","ручная сушка", date()),
  ("0","60","bone","кость", date()),
  ("0","61","shoelace","шнурки", date()),
  ("0","62","to wave","причесывать", date()),
  ("0","63","hide","спрятать", date()),
  ("0","64","behind","позади", date()),
  ("0","65","scratch","царапать, скрести", date()),
  ("0","66","soon","скоро", date()),
  ("0","67","leave","покинуть", date()),
  ("0","68","dry goods","сухие вещи, товары", date()),
  ("0","69","pantry","кладовая", date()),
  ("0","70","a toaster oven","тостер", date()),
  ("0","71","microwave","микроволновка", date()),
  ("0","72","a paper towel rack","держатель для бумажного полотенца", date()),
  ("0","73","paper towel","бумажное полотенце", date()),
  ("0","74","electrick kettle","электро чайник", date()),
  ("0","75","dish washer soap / detergent","мыло для мытья посуды / моющее средство", date()),
  ("0","76","disher","", date()),
  ("0","77","paltes","тарелки", date()),
  ("0","78","wine glass","стаканы для вина", date()),
  ("0","79","regular glass","обычные стаканы", date()),
  ("0","80","bowl","пиала", date()),
  ("0","81","mug","кружка", date()),
  ("0","82","a shoe rack","подставка для обуви", date()),
  ("0","83","living room","гостинная", date()),
  ("0","84","vanish","исчезнуть, пропасть", date()),
  ("0","85","watch out","смотри", date()),
  ("0","86","socks","носки", date()),
  ("0","87","I guess","догадываться, думать", date()),
  ("0","88","buddy","дружище", date()),
  ("0","89","wash out","отмывать", date()),
  ("0","90","paranoid","параноик", date()),
  ("0","91","to sneez","чихнуть", date()),
  ("0","92","bender","маг", date()),
  ("0","93","to freez","замерзнуть", date()),
  ("0","94","truly","вправду", date()),
  ("0","95","to fail","провалиться, потерпеть неудачу", date()),
  ("0","96","honor","честь, уважение", date()),
  ("0","97","curious","любопытный", date()),
  ("0","98","entire","весь", date()),
  ("0","99","extinct","угасший, вымерший", date()),
  ("0","100","stab","удар, попытка", date()),

  ("1","0","paranoid","параноик", date()),
  ("1","1","to sneez","чихнуть", date()),
  ("1","2","bender","маг", date()),
  ("1","3","to freez","замерзнуть", date()),
  ("1","4","truly","вправду", date()),
  ("1","5","to fail","провалиться, потерпеть неудачу", date()),
  ("1","6","honor","честь, уважение", date()),
  ("1","7","curious","любопытный", date()),
  ("1","8","entire","весь", date()),
  ("1","9","extinct","угасший, вымерший", date()),
  ("1","10","stab","удар, попытка", date());