import sqlite3 as sq
# Для заполнения таблицы words тестовыми данными.

words = [  
  {
    'word_id': 0,
    'eng_word': 'fridge',
    'rus_word': 'холодильник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 1,
    'eng_word': 'freezer',
    'rus_word': 'морозильник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 2,
    'eng_word': 'magnets',
    'rus_word': 'магниты',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 3,
    'eng_word': 'dining room table',
    'rus_word': 'стол для трапез',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 4,
    'eng_word': 'kitchen chairs',
    'rus_word': 'кухонные стулья',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 5,
    'eng_word': 'dining room chairs',
    'rus_word': 'кухонные стулья',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 6,
    'eng_word': 'high chair',
    'rus_word': 'стул для ребёнка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 7,
    'eng_word': 'a stand-alone hight chair',
    'rus_word': 'отдельно стоящий стул для ребёнка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 8,
    'eng_word': 'kitchen counter',
    'rus_word': 'стол для резки, готовки пищи',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 9,
    'eng_word': 'fruit tray',
    'rus_word': 'система подносов для фруктов',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 10,
    'eng_word': 'tangerine',
    'rus_word': 'мандарин',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 11,
    'eng_word': 'coaster',
    'rus_word': 'подставка для стаканов',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 12,
    'eng_word': 'coffee grinder',
    'rus_word': 'кофемолка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 13,
    'eng_word': 'coffee bean',
    'rus_word': 'кофейное зерно',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 14,
    'eng_word': 'sippy cup',
    'rus_word': 'кружка-непроливайка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 15,
    'eng_word': 'chees grater',
    'rus_word': 'тёрка для сыра',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 16,
    'eng_word': 'knives',
    'rus_word': 'ножи',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 17,
    'eng_word': 'measuring cups',
    'rus_word': 'мерные стаканьчики',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 18,
    'eng_word': 'tablespons',
    'rus_word': 'столовые ложки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 19,
    'eng_word': 'teaspons',
    'rus_word': 'чайные ложки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 20,
    'eng_word': 'condiment',
    'rus_word': 'специи',
    'word_description': '',
    'word_examples': '',
  },  
  {
    'word_id': 21,
    'eng_word': 'honey',
    'rus_word': 'мёд',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 22,
    'eng_word': 'balsamic vinegar',
    'rus_word': 'бальзамический уксус',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 23,
    'eng_word': 'chopsticks',
    'rus_word': 'палочки для еды, китайские палочки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 24,
    'eng_word': 'salt',
    'rus_word': 'соль',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 25,
    'eng_word': 'olive oil',
    'rus_word': 'оливковое масло',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 26,
    'eng_word': 'green thumb',
    'rus_word': '',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 27,
    'eng_word': 'oven',
    'rus_word': 'духовка / вся плита',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 28,
    'eng_word': 'stovetop',
    'rus_word': 'плита / верхняя часть плиты',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 29,
    'eng_word': 'burner',
    'rus_word': 'комфорка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 30,
    'eng_word': 'cooker',
    'rus_word': 'плита + духовка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 31,
    'eng_word': 'nobs',
    'rus_word': 'переключатели на плите',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 32,
    'eng_word': 'stickler / picky',
    'rus_word': 'ярый сторонник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 33,
    'eng_word': 'pot',
    'rus_word': 'кастрюля',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 34,
    'eng_word': 'pan',
    'rus_word': 'сковорода',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 35,
    'eng_word': 'a glass lid',
    'rus_word': 'стеклянная крышка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 36,
    'eng_word': 'butternut squash',
    'rus_word': 'тыква с орехами',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 37,
    'eng_word': 'butternut',
    'rus_word': 'ореховый',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 38,
    'eng_word': 'squash',
    'rus_word': 'кабачек',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 39,
    'eng_word': 'oven mitts',
    'rus_word': 'перчатки для духовки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 40,
    'eng_word': 'spice rack/cabin',
    'rus_word': 'комната для специй',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 41,
    'eng_word': 'spice shelf',
    'rus_word': 'полка для специй',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 42,
    'eng_word': 'tea',
    'rus_word': 'чай',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 43,
    'eng_word': 'cook book',
    'rus_word': 'кулинарная книга',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 44,
    'eng_word': 'dirty dishes',
    'rus_word': 'грязная посуда',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 45,
    'eng_word': 'a sink',
    'rus_word': 'раковина',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 46,
    'eng_word': 'faucet',
    'rus_word': 'смеситель',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 47,
    'eng_word': 'strainer',
    'rus_word': 'друшлак',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 48,
    'eng_word': 'colander',
    'rus_word': 'сито',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 49,
    'eng_word': 'dishwasher',
    'rus_word': 'посудомойка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 50,
    'eng_word': 'air conditioner',
    'rus_word': 'кондиционер',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 51,
    'eng_word': 'heating',
    'rus_word': 'отопление',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 52,
    'eng_word': '[cloth] washer',
    'rus_word': 'стриальная машина',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 53,
    'eng_word': 'dryer',
    'rus_word': 'сушилка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 54,
    'eng_word': 'table top dish washer',
    'rus_word': 'настольная посудомойка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 55,
    'eng_word': 'dish rack',
    'rus_word': 'стойка для посуды',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 56,
    'eng_word': 'rack',
    'rus_word': 'стеллаж',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 57,
    'eng_word': 'shelf',
    'rus_word': 'полка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 58,
    'eng_word': 'hand wash',
    'rus_word': 'ручшая стрика, мойка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 59,
    'eng_word': 'hand dry',
    'rus_word': 'ручная сушка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 60,
    'eng_word': 'bone',
    'rus_word': 'кость',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 61,
    'eng_word': 'shoelace',
    'rus_word': 'шнурки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 62,
    'eng_word': 'to wave',
    'rus_word': 'причесывать',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 63,
    'eng_word': 'hide',
    'rus_word': 'спрятать',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 64,
    'eng_word': 'behind',
    'rus_word': 'позади',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 65,
    'eng_word': 'scratch',
    'rus_word': 'царапать, скрести',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 66,
    'eng_word': 'soon',
    'rus_word': 'скоро',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 67,
    'eng_word': 'leave',
    'rus_word': 'покинуть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 68,
    'eng_word': 'dry goods',
    'rus_word': 'сухие вещи, товары',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 69,
    'eng_word': 'pantry',
    'rus_word': 'кладовая',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 70,
    'eng_word': 'a toaster oven',
    'rus_word': 'тостер',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 71,
    'eng_word': 'microwave',
    'rus_word': 'микроволновка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 72,
    'eng_word': 'a paper towel rack',
    'rus_word': 'держатель для бумажного полотенца',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 73,
    'eng_word': 'paper towel',
    'rus_word': 'бумажное полотенце',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 74,
    'eng_word': 'electrick kettle',
    'rus_word': 'электро чайник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 75,
    'eng_word': 'dish washer soap / detergent',
    'rus_word': 'мыло для мытья посуды / моющее средство',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 76,
    'eng_word': 'disher',
    'rus_word': '',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 77,
    'eng_word': 'paltes',
    'rus_word': 'тарелки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 78,
    'eng_word': 'wine glass',
    'rus_word': 'стаканы для вина',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 79,
    'eng_word': 'regular glass',
    'rus_word': 'обычные стаканы',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 80,
    'eng_word': 'bowl',
    'rus_word': 'пиала',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 81,
    'eng_word': 'mug',
    'rus_word': 'кружка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 82,
    'eng_word': 'a shoe rack',
    'rus_word': 'подставка для обуви',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 83,
    'eng_word': 'living room',
    'rus_word': 'гостинная',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 84,
    'eng_word': 'vanish',
    'rus_word': 'исчезнуть, пропасть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 85,
    'eng_word': 'watch out',
    'rus_word': 'смотри',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 86,
    'eng_word': 'socks',
    'rus_word': 'носки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 87,
    'eng_word': 'I guess',
    'rus_word': 'догадываться, думать',
    'word_description': '',
    'word_examples': '',
  },
  
  {
    'word_id': 88,
    'eng_word': 'buddy',
    'rus_word': 'дружище',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 89,
    'eng_word': 'wash out',
    'rus_word': 'отмывать',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 90,
    'eng_word': 'paranoid',
    'rus_word': 'параноик',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 91,
    'eng_word': 'to sneez',
    'rus_word': 'чихнуть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 92,
    'eng_word': 'bender',
    'rus_word': 'маг',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 93,
    'eng_word': 'to freez',
    'rus_word': 'замерзнуть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 94,
    'eng_word': 'truly',
    'rus_word': 'вправду',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 95,
    'eng_word': 'to fail',
    'rus_word': 'провалиться, потерпеть неудачу',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 96,
    'eng_word': 'honor',
    'rus_word': 'честь, уважение',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 97,
    'eng_word': 'curious',
    'rus_word': 'любопытный',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 98,
    'eng_word': 'entire',
    'rus_word': 'весь',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 99,
    'eng_word': 'extinct',
    'rus_word': 'угасший, вымерший',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_id': 100,
    'eng_word': 'stab',
    'rus_word': 'удар, попытка',
    'word_description': '',
    'word_examples': '',
  },
]

def transfer_to_db():
  con = sq.connect('words.db')
  cur = con.cursor()

  for word in words:
    query = f'''INSERT INTO words (id, eng_word, rus_word, add_date) VALUES(
      '{word['word_id']}',
      '{word['eng_word']}',
      '{word['rus_word']}',
      date()
    );'''
    cur.execute(query)
  
  cur.execute('COMMIT;')
  con.close()

# Для заполнения таблицы user_words тестовыми данными.
words = [  
  {
    'word_number': 0,
    'user_id': 0,
    'eng_word': 'fridge',
    'rus_word': 'холодильник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 1,
    'user_id': 0,
    'eng_word': 'freezer',
    'rus_word': 'морозильник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 2,
    'user_id': 0,
    'eng_word': 'magnets',
    'rus_word': 'магниты',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 3,
    'user_id': 0,
    'eng_word': 'dining room table',
    'rus_word': 'стол для трапез',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 4,
    'user_id': 0,
    'eng_word': 'kitchen chairs',
    'rus_word': 'кухонные стулья',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 5,
    'user_id': 0,
    'eng_word': 'dining room chairs',
    'rus_word': 'кухонные стулья',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 6,
    'user_id': 0,
    'eng_word': 'high chair',
    'rus_word': 'стул для ребёнка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 7,
    'user_id': 0,
    'eng_word': 'a stand-alone hight chair',
    'rus_word': 'отдельно стоящий стул для ребёнка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 8,
    'user_id': 0,
    'eng_word': 'kitchen counter',
    'rus_word': 'стол для резки, готовки пищи',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 9,
    'user_id': 0,
    'eng_word': 'fruit tray',
    'rus_word': 'система подносов для фруктов',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 10,
    'user_id': 0,
    'eng_word': 'tangerine',
    'rus_word': 'мандарин',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 11,
    'user_id': 0,
    'eng_word': 'coaster',
    'rus_word': 'подставка для стаканов',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 12,
    'user_id': 0,
    'eng_word': 'coffee grinder',
    'rus_word': 'кофемолка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 13,
    'user_id': 0,
    'eng_word': 'coffee bean',
    'rus_word': 'кофейное зерно',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 14,
    'user_id': 0,
    'eng_word': 'sippy cup',
    'rus_word': 'кружка-непроливайка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 15,
    'user_id': 0,
    'eng_word': 'chees grater',
    'rus_word': 'тёрка для сыра',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 16,
    'user_id': 0,
    'eng_word': 'knives',
    'rus_word': 'ножи',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 17,
    'user_id': 0,
    'eng_word': 'measuring cups',
    'rus_word': 'мерные стаканьчики',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 18,
    'user_id': 0,
    'eng_word': 'tablespons',
    'rus_word': 'столовые ложки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 19,
    'user_id': 0,
    'eng_word': 'teaspons',
    'rus_word': 'чайные ложки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 20,
    'user_id': 0,
    'eng_word': 'condiment',
    'rus_word': 'специи',
    'word_description': '',
    'word_examples': '',
  },  
  {
    'word_number': 21,
    'user_id': 0,
    'eng_word': 'honey',
    'rus_word': 'мёд',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 22,
    'user_id': 0,
    'eng_word': 'balsamic vinegar',
    'rus_word': 'бальзамический уксус',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 23,
    'user_id': 0,
    'eng_word': 'chopsticks',
    'rus_word': 'палочки для еды, китайские палочки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 24,
    'user_id': 0,
    'eng_word': 'salt',
    'rus_word': 'соль',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 25,
    'user_id': 0,
    'eng_word': 'olive oil',
    'rus_word': 'оливковое масло',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 26,
    'user_id': 0,
    'eng_word': 'green thumb',
    'rus_word': '',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 27,
    'user_id': 0,
    'eng_word': 'oven',
    'rus_word': 'духовка / вся плита',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 28,
    'user_id': 0,
    'eng_word': 'stovetop',
    'rus_word': 'плита / верхняя часть плиты',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 29,
    'user_id': 0,
    'eng_word': 'burner',
    'rus_word': 'комфорка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 30,
    'user_id': 0,
    'eng_word': 'cooker',
    'rus_word': 'плита + духовка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 31,
    'user_id': 0,
    'eng_word': 'nobs',
    'rus_word': 'переключатели на плите',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 32,
    'user_id': 0,
    'eng_word': 'stickler / picky',
    'rus_word': 'ярый сторонник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 33,
    'user_id': 0,
    'eng_word': 'pot',
    'rus_word': 'кастрюля',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 34,
    'user_id': 0,
    'eng_word': 'pan',
    'rus_word': 'сковорода',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 35,
    'user_id': 0,
    'eng_word': 'a glass lid',
    'rus_word': 'стеклянная крышка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 36,
    'user_id': 0,
    'eng_word': 'butternut squash',
    'rus_word': 'тыква с орехами',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 37,
    'user_id': 0,
    'eng_word': 'butternut',
    'rus_word': 'ореховый',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 38,
    'user_id': 0,
    'eng_word': 'squash',
    'rus_word': 'кабачек',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 39,
    'user_id': 0,
    'eng_word': 'oven mitts',
    'rus_word': 'перчатки для духовки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 40,
    'user_id': 0,
    'eng_word': 'spice rack/cabin',
    'rus_word': 'комната для специй',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 41,
    'user_id': 0,
    'eng_word': 'spice shelf',
    'rus_word': 'полка для специй',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 42,
    'user_id': 0,
    'eng_word': 'tea',
    'rus_word': 'чай',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 43,
    'user_id': 0,
    'eng_word': 'cook book',
    'rus_word': 'кулинарная книга',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 44,
    'user_id': 0,
    'eng_word': 'dirty dishes',
    'rus_word': 'грязная посуда',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 45,
    'user_id': 0,
    'eng_word': 'a sink',
    'rus_word': 'раковина',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 46,
    'user_id': 0,
    'eng_word': 'faucet',
    'rus_word': 'смеситель',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 47,
    'user_id': 0,
    'eng_word': 'strainer',
    'rus_word': 'друшлак',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 48,
    'user_id': 0,
    'eng_word': 'colander',
    'rus_word': 'сито',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 49,
    'user_id': 0,
    'eng_word': 'dishwasher',
    'rus_word': 'посудомойка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 50,
    'user_id': 0,
    'eng_word': 'air conditioner',
    'rus_word': 'кондиционер',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 51,
    'user_id': 0,
    'eng_word': 'heating',
    'rus_word': 'отопление',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 52,
    'user_id': 0,
    'eng_word': '[cloth] washer',
    'rus_word': 'стриальная машина',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 53,
    'user_id': 0,
    'eng_word': 'dryer',
    'rus_word': 'сушилка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 54,
    'user_id': 0,
    'eng_word': 'table top dish washer',
    'rus_word': 'настольная посудомойка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 55,
    'user_id': 0,
    'eng_word': 'dish rack',
    'rus_word': 'стойка для посуды',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 56,
    'user_id': 0,
    'eng_word': 'rack',
    'rus_word': 'стеллаж',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 57,
    'user_id': 0,
    'eng_word': 'shelf',
    'rus_word': 'полка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 58,
    'user_id': 0,
    'eng_word': 'hand wash',
    'rus_word': 'ручшая стрика, мойка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 59,
    'user_id': 0,
    'eng_word': 'hand dry',
    'rus_word': 'ручная сушка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 60,
    'user_id': 0,
    'eng_word': 'bone',
    'rus_word': 'кость',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 61,
    'user_id': 0,
    'eng_word': 'shoelace',
    'rus_word': 'шнурки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 62,
    'user_id': 0,
    'eng_word': 'to wave',
    'rus_word': 'причесывать',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 63,
    'user_id': 0,
    'eng_word': 'hide',
    'rus_word': 'спрятать',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 64,
    'user_id': 0,
    'eng_word': 'behind',
    'rus_word': 'позади',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 65,
    'user_id': 0,
    'eng_word': 'scratch',
    'rus_word': 'царапать, скрести',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 66,
    'user_id': 0,
    'eng_word': 'soon',
    'rus_word': 'скоро',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 67,
    'user_id': 0,
    'eng_word': 'leave',
    'rus_word': 'покинуть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 68,
    'user_id': 0,
    'eng_word': 'dry goods',
    'rus_word': 'сухие вещи, товары',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 69,
    'user_id': 0,
    'eng_word': 'pantry',
    'rus_word': 'кладовая',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 70,
    'user_id': 0,
    'eng_word': 'a toaster oven',
    'rus_word': 'тостер',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 71,
    'user_id': 0,
    'eng_word': 'microwave',
    'rus_word': 'микроволновка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 72,
    'user_id': 0,
    'eng_word': 'a paper towel rack',
    'rus_word': 'держатель для бумажного полотенца',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 73,
    'user_id': 0,
    'eng_word': 'paper towel',
    'rus_word': 'бумажное полотенце',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 74,
    'user_id': 0,
    'eng_word': 'electrick kettle',
    'rus_word': 'электро чайник',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 75,
    'user_id': 0,
    'eng_word': 'dish washer soap / detergent',
    'rus_word': 'мыло для мытья посуды / моющее средство',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 76,
    'user_id': 0,
    'eng_word': 'disher',
    'rus_word': '',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 77,
    'user_id': 0,
    'eng_word': 'paltes',
    'rus_word': 'тарелки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 78,
    'user_id': 0,
    'eng_word': 'wine glass',
    'rus_word': 'стаканы для вина',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 79,
    'user_id': 0,
    'eng_word': 'regular glass',
    'rus_word': 'обычные стаканы',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 80,
    'user_id': 0,
    'eng_word': 'bowl',
    'rus_word': 'пиала',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 81,
    'user_id': 0,
    'eng_word': 'mug',
    'rus_word': 'кружка',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 82,
    'user_id': 0,
    'eng_word': 'a shoe rack',
    'rus_word': 'подставка для обуви',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 83,
    'user_id': 0,
    'eng_word': 'living room',
    'rus_word': 'гостинная',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 84,
    'user_id': 0,
    'eng_word': 'vanish',
    'rus_word': 'исчезнуть, пропасть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 85,
    'user_id': 0,
    'eng_word': 'watch out',
    'rus_word': 'смотри',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 86,
    'user_id': 0,
    'eng_word': 'socks',
    'rus_word': 'носки',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 87,
    'user_id': 0,
    'eng_word': 'I guess',
    'rus_word': 'догадываться, думать',
    'word_description': '',
    'word_examples': '',
  },
  
  {
    'word_number': 88,
    'user_id': 0,
    'eng_word': 'buddy',
    'rus_word': 'дружище',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 89,
    'user_id': 0,
    'eng_word': 'wash out',
    'rus_word': 'отмывать',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 90,
    'user_id': 0,
    'eng_word': 'paranoid',
    'rus_word': 'параноик',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 91,
    'user_id': 0,
    'eng_word': 'to sneez',
    'rus_word': 'чихнуть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 92,
    'user_id': 0,
    'eng_word': 'bender',
    'rus_word': 'маг',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 93,
    'user_id': 0,
    'eng_word': 'to freez',
    'rus_word': 'замерзнуть',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 94,
    'user_id': 0,
    'eng_word': 'truly',
    'rus_word': 'вправду',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 95,
    'user_id': 0,
    'eng_word': 'to fail',
    'rus_word': 'провалиться, потерпеть неудачу',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 96,
    'user_id': 0,
    'eng_word': 'honor',
    'rus_word': 'честь, уважение',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 97,
    'user_id': 0,
    'eng_word': 'curious',
    'rus_word': 'любопытный',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 98,
    'user_id': 0,
    'eng_word': 'entire',
    'rus_word': 'весь',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 99,
    'user_id': 0,
    'eng_word': 'extinct',
    'rus_word': 'угасший, вымерший',
    'word_description': '',
    'word_examples': '',
  },
  {
    'word_number': 100,
    'user_id': 0,
    'eng_word': 'stab',
    'rus_word': 'удар, попытка',
    'word_description': '',
    'word_examples': '',
  },
]

def transfer_to_db_user_words():
  con = sq.connect('words.db')
  cur = con.cursor()

  # '{word['word_number']}'
  for word in words:
    print(f'{word['word_number'] = }')
    query = f'''INSERT INTO user_words (user_id, word_number, eng_word, rus_word, add_date, last_repeat_date) VALUES(
      '{word['user_id']}',
      7,
      '{word['eng_word']}',
      '{word['rus_word']}',
      date(),
      date()
    );'''
    cur.execute(query)
  
  # cur.execute('COMMIT;')
  con.commit()
  con.close()

def print_query_for_test_words():
  sql = 'INSERT INTO user_words (user_id, word_number, eng_word, rus_word, add_date) VALUES\n'
  for word in words:
    sql += f'("{word['user_id']}","{word['word_number']}","{word['eng_word']}","{word['rus_word']}", date()),\n'
  print(sql)

print_query_for_test_words()